on:
  pull_request:
    branches:
      - main
name: SonarQube pull request decoration
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
