spring:
  application:
    name: spring-boot-example
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      instance-id: ${random.value}
