on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module path"
        required: true
      projectName:
        description: "Project name"
        required: true
      imageName:
        description: "Image name"
        required: true
name: Harbor에 도커 이미지 배포하기
jobs:
  build:
    name: push-image-on-harbor
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: yyyyMMDDHHmmss
          utcOffset: "+09:00"
      - name: Get deploy version
        run: echo "deployment-version=${{ steps.current-time.outputs.formattedTime }}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Deploy api server image
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: true
          arguments: |
            :${{ github.event.inputs.module }}:jib
            -DsendCredentialsOverHttp=true
            -Djib.from.auth.username=${{ secrets.HARBOR_USERNAME }}
            -Djib.from.auth.password=${{ secrets.HARBOR_PASSWORD }}
            -Djib.to.image=10.10.10.6:80/${{ github.event.inputs.projectName }}/${{ github.event.inputs.imageName }}
            -Djib.to.tags=${{ env.deployment-version }},latest
            -Djib.to.auth.username=${{ secrets.HARBOR_USERNAME }}
            -Djib.to.auth.password=${{ secrets.HARBOR_PASSWORD }}
