on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - spring-boot-on-kubernetes/**
name: Spring boot example 배포 파이프라인
jobs:
  deploy-image:
    runs-on: self-hosted
    steps:
      - name: hello
        run: echo 'hello'
